name: ProjectCard Auto Labels

on:
  project_card:
    types: [moved]

jobs:
  projectcardautolabel_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run ProjectCard AutoLabel
      id: runprojectcardautolabel
      uses: Matticusau/projectcard-autolabel@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        autolabel-config: '[{"column":"In Progress", "add_labels":["in-progress"], "remove_labels":["to-do","no-status","icebox","blocked"]}]'
        projectfilter-config: '{"include":["9"]}'
